# Generated by Django 4.1.7 on 2023-02-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.FilePathField(verbose_name="/projects/img"),
        ),
    ]
