# Generated by Django 4.1.7 on 2023-02-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_alter_project_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.CharField(max_length=100),
        ),
    ]
